<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="1">

  <testsuite name="function2_boundary.function2_boundary_13.test"
    errors="0" failures="1" hostname="" id="" package="function2_boundary" skipped="0"
    tests="1" time="6.373" timestamp="">
  
    <testcase name="test_case_01" classname="function2_boundary.function2_boundary_13.test" time="6.373" assertions="1">  <failure message="Testing if element [0;33m&lt;#result2&gt;[0m contains text [0;33m&#39;invalid&#39;[0m in 5000ms - expected [0;32m&#34;contains text &#39;invalid&#39;&#34;[0m but got: [0;31m&#34;does not contain &#39;invalid&#39;&#34;[0m [0;90m(5217ms)[0m">    at NightwatchAPI.&lt;anonymous&gt; (D:\goodgoodstudy\3-2\软件测试\作业一\NightwatchSimulator\case\function2_boundary\function2_boundary_13.test.js:31:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>

    
      <failure message="    at NightwatchAPI.&lt;anonymous&gt; (D:\goodgoodstudy\3-2\软件测试\作业一\NightwatchSimulator\case\function2_boundary\function2_boundary_13.test.js:31:23)">    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>
    </testcase>
  

  

  
  </testsuite>
</testsuites>
